# Generated by Django 4.0.3 on 2022-05-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_view_cnt_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='scrap',
            field=models.BooleanField(default=False),
        ),
    ]
